/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
// int puts(const char *s);
// size_t strlen(const char *s);
// void setbuf(FILE *stream, char *buf);
// int printf(const char *format, ...);
// __int64 __isoc99_scanf(const char *, ...); weak
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void *sub_10C0();
__int64 sub_10F0();
void *sub_1130();
__int64 sub_1180();
signed __int64 __fastcall _do_global_ctors_aux();
int __fastcall check(const char *a1);
void init();
int __fastcall main(int argc, const char **argv, const char **envp);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int _cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *_dso_handle = &_dso_handle; // idb
_UNKNOWN data_start; // weak
_BYTE key[8] = { -88, -106, 79, 127, 62, -108, 10, -107 }; // weak
_UNKNOWN _bss_start; // weak
FILE *stdout; // idb
FILE *stdin; // idb
FILE *stderr; // idb
char byte_4088; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 40E0: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001090) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, 0, 0, a3, &v5);
  __halt();
}
// 109A: positive sp value 8 has been found
// 10A1: variable 'v3' is possibly undefined

//----- (00000000000010C0) ----------------------------------------------------
void *sub_10C0()
{
  return &_bss_start;
}

//----- (00000000000010F0) ----------------------------------------------------
__int64 sub_10F0()
{
  return 0;
}

//----- (0000000000001130) ----------------------------------------------------
void *sub_1130()
{
  void *result; // rax

  if ( !byte_4088 )
  {
    if ( &_cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = sub_10C0();
    byte_4088 = 1;
  }
  return result;
}
// 4088: using guessed type char byte_4088;

//----- (0000000000001180) ----------------------------------------------------
// attributes: thunk
__int64 sub_1180()
{
  return sub_10F0();
}

//----- (0000000000001189) ----------------------------------------------------
signed __int64 __fastcall _do_global_ctors_aux()
{
  unsigned __int64 v0; // r10
  signed __int64 result; // rax
  int i; // [rsp+0h] [rbp-10h]
  _QWORD *v3; // [rsp+8h] [rbp-8h]

  result = sys_ptrace(0, 0, 0, v0);
  result = (unsigned int)result;
  if ( (_DWORD)result != -1 )
  {
    result = (signed __int64)&data_start;
    v3 = &data_start;
    for ( i = 0; i <= 255; ++i )
    {
      result = 0x950A943E7F4F96A8LL;
      if ( *v3 == 0x950A943E7F4F96A8LL )
      {
        result = (signed __int64)v3;
        *v3 ^= 0x119011901190119uLL;
        return result;
      }
      ++v3;
    }
  }
  return result;
}
// 11A1: variable 'v0' is possibly undefined

//----- (000000000000120B) ----------------------------------------------------
int __fastcall check(const char *a1)
{
  int i; // [rsp+1Ch] [rbp-14h]

  for ( i = 0; i < strlen(a1); ++i )
    a1[i] ^= key[i % 8];
  if ( *(_QWORD *)a1 == 0xA377AD570465FDF9LL )
    return puts("C'est correct !");
  else
    return puts("Essaie encore !");
}
// 4048: using guessed type _BYTE key[8];

//----- (00000000000012BF) ----------------------------------------------------
void init()
{
  setbuf(stdout, 0);
  setbuf(stdin, 0);
  setbuf(stderr, 0);
}

//----- (0000000000001302) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  char v4[104]; // [rsp+10h] [rbp-70h] BYREF
  unsigned __int64 v5; // [rsp+78h] [rbp-8h]

  v5 = __readfsqword(0x28u);
  init();
  printf("Key: ");
  __isoc99_scanf("%s", v4);
  check(v4);
  return 0;
}
// 1080: using guessed type __int64 __isoc99_scanf(const char *, ...);

//----- (0000000000001380) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=27 queued=12 decompiled=12 lumina nreq=0 worse=0 better=0
// ALL OK, 12 function(s) have been successfully decompiled
