/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
// int printf(const char *format, ...);
// char *stpcpy(char *dest, const char *src);
// int puts(const char *s);
// __int64 __isoc99_sscanf(_QWORD, const char *, ...); weak
// void __noreturn exit(int status);
// size_t strnlen(const char *string, size_t maxlen);
// __int64 __fastcall MD5_Final(_QWORD, _QWORD); weak
// __int64 __fastcall MD5_Update(_QWORD, _QWORD, _QWORD); weak
// char *strcpy(char *dest, const char *src);
// __int64 __fastcall MD5_Init(_QWORD); weak
// void *memcpy(void *dest, const void *src, size_t n);
// int _cxa_finalize(void *);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
char *sub_11D0();
__int64 sub_1200(); // weak
char *sub_1240();
__int64 __fastcall sub_1290(int a1);
__int64 __fastcall sub_12B0(int *a1, __int64 a2);
__int64 __fastcall sub_1380(char *src, __int64 a2);
bool __fastcall sub_1470(char *a1, int *a2);
void fini(void); // idb
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN main;
_UNKNOWN init;
__int64 (__fastcall *off_3DD8[2])() = { &sub_1280, &sub_1240 }; // weak
__int64 (__fastcall *off_3DE0)() = &sub_1240; // weak
void *off_4088 = &off_4088; // idb
_UNKNOWN unk_41A0; // weak
_UNKNOWN unk_43A0; // weak
char byte_44A0; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4518: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001100) ----------------------------------------------------
__int64 __fastcall main(int a1, char **a2, char **a3)
{
  int v4; // [rsp+4h] [rbp-24h] BYREF
  char v5; // [rsp+8h] [rbp-20h] BYREF
  char v6; // [rsp+Ch] [rbp-1Ch] BYREF

  if ( a1 == 1 )
  {
    printf("Usage: %s <username> <serial>\n", *a2);
  }
  else if ( a1 == 3
         && ~(strlen(a2[2]) + 1) == -28
         && (unsigned int)__isoc99_sscanf(a2[2], "%x-%x-%x", &v4, &v5, &v6) == 3 )
  {
    if ( sub_1470(a2[1], &v4) )
      puts("Ok, you can validate the challenge with this serial number (in uppercase).");
    else
      puts("Try again.");
  }
  return 0;
}
// 1060: using guessed type __int64 __isoc99_sscanf(_QWORD, const char *, ...);

//----- (00000000000011A0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, (void (*)(void))init, fini, a3, &v5);
  __halt();
}
// 11A6: positive sp value 8 has been found
// 11AD: variable 'v3' is possibly undefined

//----- (00000000000011D0) ----------------------------------------------------
char *sub_11D0()
{
  return &byte_44A0;
}
// 44A0: using guessed type char byte_44A0;

//----- (0000000000001200) ----------------------------------------------------
__int64 sub_1200()
{
  return 0;
}
// 1200: using guessed type __int64 sub_1200();

//----- (0000000000001240) ----------------------------------------------------
char *sub_1240()
{
  char *result; // rax

  if ( !byte_44A0 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_4088);
    result = sub_11D0();
    byte_44A0 = 1;
  }
  return result;
}
// 44A0: using guessed type char byte_44A0;

//----- (0000000000001290) ----------------------------------------------------
__int64 __fastcall sub_1290(int a1)
{
  unsigned int i; // r8d

  for ( i = 0; a1; a1 &= a1 - 1 )
    ++i;
  return i;
}

//----- (00000000000012B0) ----------------------------------------------------
__int64 __fastcall sub_12B0(int *a1, __int64 a2)
{
  __int64 v2; // rcx
  int v3; // ebp
  int v4; // r11d
  unsigned int v5; // ebx
  __int64 v6; // rdx
  __int64 v7; // rcx
  unsigned __int8 v8; // al
  unsigned __int8 v9; // r9
  __int64 v10; // rcx
  int v11; // r12d
  __int64 v12; // rdx
  __int64 v13; // rcx
  __int64 result; // rax
  int *v15; // r10
  unsigned __int8 v16; // r9
  __int64 v17; // rcx

  v2 = 0;
  v3 = 0;
  v4 = *a1;
  v5 = a1[1];
  do
  {
    sub_1290(v4 & *(_DWORD *)(a2 + v2));
    v8 = sub_1290(v5 & *(_DWORD *)(v6 + v7));
    v2 = v10 + 4;
    v3 = (v8 ^ v9) & 1 ^ (2 * v3);
  }
  while ( v2 != 128 );
  v11 = 0;
  do
  {
    sub_1290(v4 & *(_DWORD *)(a2 + v2));
    result = sub_1290(v5 & *(_DWORD *)(v12 + v13));
    v2 = v17 + 4;
    v11 = ((unsigned __int8)result ^ v16) & 1 ^ (2 * v11);
  }
  while ( v2 != 256 );
  *v15 = v3;
  v15[1] = v11;
  return result;
}
// 12CD: variable 'v4' is possibly undefined
// 12D5: variable 'v6' is possibly undefined
// 12D5: variable 'v7' is possibly undefined
// 12E5: variable 'v10' is possibly undefined
// 12E2: variable 'v9' is possibly undefined
// 130E: variable 'v12' is possibly undefined
// 130E: variable 'v13' is possibly undefined
// 131E: variable 'v17' is possibly undefined
// 131B: variable 'v16' is possibly undefined
// 1333: variable 'v15' is possibly undefined

//----- (0000000000001380) ----------------------------------------------------
__int64 __fastcall sub_1380(char *src, __int64 a2)
{
  char *v3; // rbx
  char *v4; // rax
  char *v5; // rdx
  char v6; // cl
  char v7; // si
  _BYTE v9[96]; // [rsp+0h] [rbp-208h] BYREF
  char dest[128]; // [rsp+60h] [rbp-1A8h] BYREF
  char v11[296]; // [rsp+E0h] [rbp-128h] BYREF

  if ( strnlen(src, 0x80u) == 128 )
    exit(2);
  memset(v11, 0, 0x100u);
  v3 = stpcpy(dest, src);
  memcpy(v11, dest, v3 - dest + 1);
  if ( (unsigned __int64)(v3 - dest) > 1 )
  {
    v4 = v3 - 1;
    if ( v3 - 1 > dest )
    {
      v5 = dest;
      do
      {
        v6 = *v4;
        v7 = *v5;
        --v4;
        ++v5;
        v4[1] = v7;
        *(v5 - 1) = v6;
      }
      while ( v5 < v4 );
    }
  }
  strcpy(&v11[v3 - dest], dest);
  MD5_Init(v9);
  MD5_Update(v9, v11, 256);
  return MD5_Final(a2, v9);
}
// 10A0: using guessed type __int64 __fastcall MD5_Final(_QWORD, _QWORD);
// 10B0: using guessed type __int64 __fastcall MD5_Update(_QWORD, _QWORD, _QWORD);
// 10D0: using guessed type __int64 __fastcall MD5_Init(_QWORD);

//----- (0000000000001470) ----------------------------------------------------
bool __fastcall sub_1470(char *a1, int *a2)
{
  bool result; // al
  _DWORD v3[6]; // [rsp+0h] [rbp-18h] BYREF

  sub_1380(a1, (__int64)v3);
  sub_12B0(a2, (__int64)&unk_43A0);
  sub_12B0(a2 + 1, (__int64)&unk_41A0);
  result = 0;
  if ( *a2 == v3[0] && a2[1] == v3[1] )
    return a2[2] == v3[2];
  return result;
}

//----- (00000000000014E0) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 v4; // rbp
  __int64 i; // rbx

  init_proc();
  v4 = &off_3DE0 - off_3DD8;
  if ( v4 )
  {
    for ( i = 0; i != v4; ++i )
      ((void (__fastcall *)(_QWORD, __int64, __int64))off_3DD8[i])(a1, a2, a3);
  }
}
// 3DD8: using guessed type __int64 (__fastcall *off_3DD8[2])();
// 3DE0: using guessed type __int64 (__fastcall *off_3DE0)();

//----- (0000000000001544) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=43 queued=13 decompiled=13 lumina nreq=0 worse=0 better=0
// ALL OK, 13 function(s) have been successfully decompiled
